name: Mark stale issues and auto close if inactive

on:
#   schedule:
#   - cron: "30 1 * * *"
  workflow_dispatch:  

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        debug-only: true
        enable-statistics: true
        stale-issue-label: 'stale'
        stale-issue-message: 'This issue is marked stale because it has not seen any activity in 365 days. It will be automatically closed in 5 days if remains inactive.'
        close-issue-message: 'This issue was closed because it has been stalled for over an 365 days without any activity.'
        days-before-issue-stale: 365
        days-before-issue-close: 5
        
